name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout 
      - run: docker compose build ml_model
      - run: docker tag ml_model lce/monrepoondockerhub
      - run: docker login -p ${{LOGIN_SECRET}}
      - run: docker push lce/monrepo      
      - run: ssh ubuntu@17.2.2.1 "docker compose pull lce/monrepoondocker"
      - run: "(re)start container"
